### ISSUE TITLE
change repo name?

### ISSUE THREAD

**Issue by elespdn** [CondorCompPhil/falcon#17]
Change repo name to pipeline_collazione, before other persons have the link?

**Comment by elespdn** [comment]
pipeline_collazione or something similar that is a bit more explicit

**Comment by LucenceIng** [comment]
It seems a good idea for me

**Comment by Jean-Baptiste-Camps** [comment]
I would vote for finding a nickname, more than a descriptive name. But we need to find an idea !

**Comment by elespdn** [comment]
Kolla

**Comment by elespdn** [comment]
No, it's already taken ....

**Comment by elespdn** [comment]
Maybe "colla"
https://en.wikipedia.org/wiki/Colla
in Italian it means "glue"
should be something like col (collation) + la (lemmatization)

**Comment by elespdn** [comment]
or something with lem + alignment (alignment covers the first phase of segments alignment and the collation itself)
_lemaligne_
:)
but the issue with 'i' and 'e' is that in English you don't know how to pronounce that ...

**Comment by elespdn** [comment]
In short, my propositions are

- colla
- lemaligne

**Comment by Jean-Baptiste-Camps** [comment]
Here a few ones from me:

- FALCON (French Ancient Litterature CollatioN ou Français ancien Lemmatisation & Collation), to keep the 'CONDOR(cet)' theme;
- Cappucino (Collation and text PProcessing Unified …) for the 'Collazione' theme

I keep looking for other ideas.

**Comment by Jean-Baptiste-Camps** [comment]
FALCON: For Automated Linguistically-equipped CollatioN ?

**Comment by elespdn** [comment]
![falconTest](https://user-images.githubusercontent.com/6794584/60394649-f3556300-9b27-11e9-8574-904dbeb97d5a.png)

**Comment by Jean-Baptiste-Camps** [comment]
Ouahou, trop bien ! C'est toi qui a fait le logo ? Ça a l'air super pro.

**Comment by LucenceIng** [comment]
C'est trop beau !

**Comment by elespdn** [comment]
Je me rejouis que ça vous plait! Fait _with a little help from my friends_

Aussi la ligne avec les termes entiers vous va? For Alignment, Lemmatization and CollatioN?

Je vous envoie une version svg dès que c'est confirmé, cela est png

**Comment by Jean-Baptiste-Camps** [comment]
Oui, de mon côté, tout me va, et on peut changer le nom du repo sans problème !

**Comment by elespdn** [comment]
Ok, done and readme updated, see #26
