### ISSUE TITLE
Freeling output

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [CondorCompPhil/falcon#23]
@elespdn 

What kind of output does Freeling serve ? Can we treat it with `xmlify` as well, in order to have the same kind of results ?

**Comment by elespdn** [comment]
Let me check ..


Il mer 26 giu 2019, 16:44 Jean-Baptiste-Camps <notifications@github.com> ha
scritto:

**Comment by elespdn** [comment]
Not sure we can apply xmlify, it is already XML. I finished this other
meeting and check more in details, bur there might be a reason why I did
not use that ..

Il mer 26 giu 2019, 16:44 Jean-Baptiste-Camps <notifications@github.com> ha
scritto:

**Comment by Jean-Baptiste-Camps** [comment]
Ok, we'll have to look if it is possible to implement something, in order to have the same full workflow with Freeling too.
